### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by YumeMichi** [xdevs23/android_packages_themes_HexoLibre#1]
Steps:
```
cd ~/omni
git clone https://github.com/xdevs23/android_packages_themes_HexoLibre.git packages/themes/HexoLibre
. build/envsetup.sh
lunch omni_onyx-userdebug
mmm -j4 packages/themes/HexoLibre
```

20 minutes passed, the build process is still running. Is there a problem with my build step?
![](https://blog.ikke.moe/images/20170509113933.png)

![](https://blog.ikke.moe/images/20170509114046.png)

**Comment by xdevs23** [comment]
That's because that version of DTT is not able to resolve all resources. But this is not even an usable thing here, this repo is just an experiment.

**Comment by YumeMichi** [comment]
Oh, I see. Thank you
